dev:
    s3_bucket: YOUR_BUCKET_NAME_HERE
    app_function: reader.app
    keep_warm: false
    extra_permissions:
        -
            Effect: Allow
            Action:
                - "polly:SynthesizeSpeech"
            Resource: "*"
